default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: demo_heroku_development
  username: postgres
  password: postgres

 
test:
  <<: *default
  database: demo_heroku_development
  username: postgres
  password: postgres


#
production:
  <<: *default
  database: demo_heroku_development
  username: postgres
  password: postgres
