# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: becf692bbbf1bea865328e56d39e330e9ea3ee622495e7fc1dc4ee71a0c5f4376dd818f060421f9238dcc5d003cbfa05e7b3511fba6460f8beb216ee3d1449e0

test:
  secret_key_base: 54eeab768e6eb1b37be4fb944aeeeee5691875061cc5de57aa78c6ec9e3881840fdf4750ac62f1dd67237c047d4ad275fa29d931076919a47787141c76e3f653

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 54eeab768e6eb1b37be4fb944aeeeee5691875061cc5de57aa78c6ec9e3881840fdf4750ac62f1dd67237c047d4ad275fa29d931076919a47787141c76e3f64f
